version: '3.4'

services:
  wealth:
    build:
      context: .
      dockerfile: Wealth/Wealth.Backend/Dockerfile
    ports:
      - "5000:80"  
  front:
    build: 
      context: Wealth/Wealth.Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
  pg:
    image: postgres:15
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
