version: '3.4'

services:
  wealth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  front:
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./Wealth/Wealth.Frontend:/src/
      - nodemodules:/src/node_modules
volumes:
    nodemodules: {}
